require('../../components/components.js')
import './index.scss'
import './assets/logo-desktop.svg'
import './assets/logo-tablet.svg'
import './assets/logo-mobile_img.svg'
import './assets/logo-mobile_text.svg'
import './assets/index-can-desktop.png'
import './assets/index-can-mobile.png'
import './assets/index-background-desktop.png'
import './assets/index-background-mobile.png'
import './assets/features-cat.svg'
import './assets/features-tiger.svg'
import './assets/link-arrow.svg'
import './assets/brief-leaf.svg'
import './assets/footer-logo.svg'
import './assets/footer-vk.svg'
import './assets/footer-fb.svg'
import './assets/footer-inst.svg'
import './assets/footer-copyright.svg'
import './assets/cat1.png'
import './assets/cat2.png'
import './assets/map-pin.png'
require('./scripts/slider')
require('./scripts/map.js')